; novotree.iss — Inno Setup 6 installer script
;
; Prerequisites:
;   1. python version.py              (generates version.iss + installer/version_info.txt)
;   2. cd frontend && npm run build   (produces frontend/dist/)
;   3. pyinstaller novotree.spec      (builds dist\novotree\)
;   4. iscc installer\novotree.iss    (builds installer\Output\novotree-setup.exe)
;
; Or run the full pipeline: .\installer\build.ps1
;
; Requires Inno Setup 6: https://jrsoftware.org/isinfo.php

; Version is read from version.iss generated by:  python version.py
#include "version.iss"

#define MyAppName       "NovoTree"
#define MyAppPublisher  "NovoSpace"
#define MyAppURL        "https://novospace.cz/novotree"
#define MyAppExeName    "novotree.exe"
; --onefile build: PyInstaller produces a single dist\novotree.exe (no
; novotree\ subfolder). build.ps1 passes --distpath installer\dist, so
; the file we ship is at installer\dist\novotree.exe — i.e. dist\novotree.exe
; relative to this .iss.
#define MyBuildDir      "dist"
; App GUID (no braces) — single source of truth, used for AppId and the
; upgrade-detection registry lookup in [Code]. Braces are added at each use
; site because the [Setup] AppId needs a doubled "{{" to escape the constant
; syntax, while the [Code] string needs a plain single "{".
#define MyAppGuid       "AF465320-1269-4CC5-8860-9C17E4BD536B"

[Setup]
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppId={{{#MyAppGuid}}

; Install to %LocalAppData%\Programs\NovoTree by default (no admin rights needed)
DefaultDirName={localappdata}\Programs\{#MyAppName}
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog

; Output
OutputDir=Output
OutputBaseFilename=novotree-{#MyAppVersion}-setup

; Compression
Compression=lzma2/ultra64
SolidCompression=yes
LZMAUseSeparateProcess=yes

; Appearance
WizardStyle=modern
SetupIconFile=novotree.ico

; Always write a setup log to %TEMP%\Setup Log YYYY-MM-DD #NNN.txt so install
; problems (e.g. an upgrade-in-place file replace) can be diagnosed after the fact.
SetupLogging=yes

; Uninstaller
UninstallDisplayName={#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}

; Running-instance handling on install:
; PyInstaller's --onefile bootloader keeps novotree.exe mapped while running,
; so Inno Setup's Restart Manager flags it as "in use" (and often lists it
; twice — the bootloader plus its own file mapping). WM_CLOSE alone doesn't
; reliably make the bootloader exit, which can cause file-replace failures
; mid-install. Belt-and-suspenders:
;   1. InitializeSetup() taskkills novotree.exe BEFORE the Restart Manager
;      scan even runs (handled in [Code] below — usually means the user
;      never sees the in-use dialog).
;   2. If anything still resists, CloseApplications=force tells Inno Setup
;      to TerminateProcess after WM_CLOSE times out instead of giving up.
CloseApplications=force
RestartApplications=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; \
  Description: "{cm:CreateDesktopIcon}"; \
  GroupDescription: "{cm:AdditionalIcons}"

[Files]
; --onefile bundle: ship a single self-contained novotree.exe.
; (Switched from --onedir specifically to keep uninstall fast — a one-dir
; bundle would mean ~10 000 small files for the uninstaller to delete with
; Windows Defender re-scanning each, taking close to a minute and making the
; uninstall window appear frozen. With one file, uninstall is near-instant.)
Source: "{#MyBuildDir}\{#MyAppExeName}"; \
  DestDir: "{app}"; \
  Flags: ignoreversion

[Icons]
; Start Menu shortcut
Name: "{autoprograms}\{#MyAppName}"; \
  Filename: "{app}\{#MyAppExeName}"

; Desktop shortcut (optional, user can deselect during install)
Name: "{autodesktop}\{#MyAppName}"; \
  Filename: "{app}\{#MyAppExeName}"; \
  Tasks: desktopicon

[Run]
; Offer to launch immediately after install
Filename: "{app}\{#MyAppExeName}"; \
  Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; \
  Flags: nowait postinstall skipifsilent

[InstallDelete]
; Upgrade-in-place cleanup. Runs as part of the normal install pass (there is NO
; separate, slow uninstaller step) so the new build never sits next to stale
; leftovers from a previous version:
;   - The single novotree.exe is overwritten by [Files] (ignoreversion), but we
;     delete it first so the claim "old files are cleared before the new ones are
;     written" is literally true rather than relying on overwrite semantics.
;   - {app}\_internal and {app}\__pycache__ only exist if an OLDER --onedir build
;     was ever installed into this folder; remove them so switching a user from an
;     old onedir layout to the current onefile bundle leaves nothing behind.
; Only the program folder ({app}) is touched. The user's tree data (their chosen
; data folder) and config (%LocalAppData%\NovoSpace\NovoTree) live elsewhere and
; are never affected.
Type: files;          Name: "{app}\{#MyAppExeName}"
Type: filesandordirs; Name: "{app}\_internal"
Type: filesandordirs; Name: "{app}\__pycache__"

[UninstallDelete]
; In --onefile mode there's no __pycache__ in the install dir to clean up
; (the bundle extracts to a temp dir on launch, not next to the exe).
; User-chosen data folder under %LocalAppData%\<their choice> is intentionally
; NOT deleted — preserved across uninstalls.

[Code]
{ Pre-install: kill any running NovoTree.
    PyInstaller's --onefile bootloader keeps novotree.exe mapped for its own
    image while running, plus pywebview's WebView2 backend spawns helper
    processes — between them, Inno Setup's Restart Manager scan reliably
    flags novotree.exe as "in use" if the user is upgrading without closing
    the previous instance first. WM_CLOSE doesn't always make the bootloader
    exit cleanly, so we just taskkill the lot. The 2>nul swallows the noisy
    error message taskkill prints when there's nothing running. }
function InitializeSetup(): Boolean;
var
  ResultCode: Integer;
begin
  Exec(ExpandConstant('{cmd}'), '/C taskkill /F /IM novotree.exe /T 2>nul',
       '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Result := True;
end;

{ Upgrade reassurance.
    We install over any existing version in place (see [InstallDelete] + the
    ignoreversion flag in [Files]) instead of running a separate uninstaller.
    That avoids a slow file-by-file removal and keeps the upgrade to a single
    fast pass. The only thing the user needs to be told is that installing over
    an existing copy is safe and leaves their tree data untouched.

    The note is shown from InitializeWizard (the very first thing at startup,
    before any wizard page) so it is impossible to miss -- unlike
    PrepareToInstall, which fires late and can flash past on a fast machine. }

{ Look up the previous install's registry key. Returns its base path, or '' if
  no previous version is registered. }
function GetUninstallKey(var Hive: Integer): String;
var
  RegKey: String;
begin
  RegKey := 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\' +
            '{{#MyAppGuid}}_is1';
  { Per-user installs (PrivilegesRequired=lowest) live under HKCU; a previous
    admin install would be under HKLM. Check both. }
  if RegKeyExists(HKCU, RegKey) then
  begin
    Hive := HKCU;
    Result := RegKey;
  end
  else if RegKeyExists(HKLM, RegKey) then
  begin
    Hive := HKLM;
    Result := RegKey;
  end
  else
    Result := '';
end;

{ True if a previous version is installed; OutVersion gets its DisplayVersion. }
function PreviousVersionInstalled(var OutVersion: String): Boolean;
var
  Hive: Integer;
  RegKey: String;
begin
  OutVersion := '';
  RegKey := GetUninstallKey(Hive);
  if RegKey = '' then
  begin
    Result := False;
    Exit;
  end;
  if not RegQueryStringValue(Hive, RegKey, 'DisplayVersion', OutVersion) then
    OutVersion := 'an earlier version';
  Result := True;
end;

{ Shown once, before any wizard page -- guaranteed visible. }
procedure InitializeWizard();
var
  OldVer: String;
begin
  if not PreviousVersionInstalled(OldVer) then
    Exit;   { fresh install -- no previous version, nothing to say }

  MsgBox(
    'NovoTree ' + OldVer + ' is already installed.' + #13#10 + #13#10
    + 'This setup will update it to version {#MyAppVersion} by installing over '
    + 'the existing version. This is perfectly safe:' + #13#10 + #13#10
    + '  -  The old program file is replaced cleanly -- no leftover or stale '
    + 'files remain.' + #13#10
    + '  -  Your family tree, photos, and database are stored separately in your '
    + 'chosen data folder and are NOT affected.' + #13#10
    + '  -  Nothing is corrupted; the system is simply updated to the new '
    + 'version.' + #13#10 + #13#10
    + 'For best results, please close NovoTree before continuing.',
    mbInformation, MB_OK);
end;

{ Uninstall progress UX:
    The bundled novotree.exe is ~30 MB. Windows Defender re-scans it before
    deletion which takes ~10-15 s. Inno Setup's progress bar is keyed on
    file count (3 files: the .exe + unins000.dat + unins000.exe), so during
    that heavy delete the bar appears frozen at ~33% — users assume the
    process is hung and may force-kill it. We overwrite Inno Setup's
    per-file status with one informative line so the user knows why.

    Caveats this code handles:
      1. ProgressBar.Style is NOT touched — that setter isn't bridged to
         Pascal Script; assigning npbstMarquee compiles but raises "Runtime
         error: Could not call proc" at uninstall time.
      2. Only the usUninstall branch is updated. usPostUninstall fires after
         the install dir is gone and the form is in a torn-down state; the
         StatusLabel setter has been observed to fail there with the same
         "Could not call proc" runtime error — Inno Setup will show its own
         "Setup successfully removed" dialog at the end anyway, so we don't
         need a "Cleanup complete." touch.
      3. The whole body is wrapped in try/except: a cosmetic UX touch must
         NEVER surface as an error dialog to the user. If the property
         bridge breaks in some future Inno Setup version, the uninstall
         still proceeds and the user just sees Inno Setup's default text. }
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  try
    if CurUninstallStep = usUninstall then begin
      UninstallProgressForm.StatusLabel.Caption :=
        'Removing NovoTree application files (~30 MB) — Windows Defender re-scans before deletion, this can take 10-15 seconds.';
    end;
  except
    // Swallow: cosmetic update only.
  end;
end;
